name       : python-pyglet
version    : 2.0.8
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/pyglet/pyglet-2.0.8.zip : c5cf9a132c1c01a67f54bf79f5a4cd8b4466d426f56852033078a3f67cd883c6
license    : BSD-3-Clause
component  : programming.python
summary    : Cross-platform windowing and multimedia library for python
description: |
    pyglet provides an object-oriented programming interface for developing games and other visually-rich applications.
builddeps  :
    - pkgconfig(glu)
rundeps    :
    - python-future
build      : |
    %python3_setup
install    : |
    %python3_install
