name       : python-pyglet
version    : 1.3.2
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/p/pyglet/pyglet-1.3.2.tar.gz : b00570e7cdf6971af8953b6ece50d83d13272afa5d1f1197c58c0f478dd17743
license    : BSD-3-Clause
component  : programming.python
summary    : Cross-platform windowing and multimedia library for python
description: |
    pyglet provides an object-oriented programming interface for developing games and other visually-rich applications.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
