name       : python-pyglet
version    : 1.3.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/pyglet/pyglet-1.3.1.tar.gz : 0a73280fa3949ea4890fee28f625c10b1e10a7cda390a08b6bce4740948167cd
license    : BSD-3-Clause
component  : programming.python
summary    : Cross-platform windowing and multimedia library for python
description: |
    pyglet provides an object-oriented programming interface for developing games and other visually-rich applications.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install

